imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

zend:
    logger:
        priority: debug
        path:     %kernel.logs_dir%/%kernel.environment%.log

assetic:
    use_controller: true
